In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [32]:
## sentences
sent=[  'the glass of milk',
         'the glass of juice',
         'the cup of tea',
         'I am a good boy',
         'I am a good developer',
         'understand the meaning of words',
         'your videos are good']

In [33]:
second_sent = ['I like the dog']

In [34]:
## Define the vocabulary size
voc_size = 10000

In [35]:
### One Hot Representation:
one_hot_repr = [one_hot(word, voc_size) for word in sent]    

In [36]:
one_hot_repr

[[2049, 9803, 1028, 4624],
 [2049, 9803, 1028, 3501],
 [2049, 5814, 1028, 1820],
 [9909, 1124, 9391, 3507, 5988],
 [9909, 1124, 9391, 3507, 4877],
 [7266, 2049, 1365, 1028, 3779],
 [3233, 3884, 7809, 3507]]

In [37]:
## word Embedding Representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [38]:
import numpy as np

In [39]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2049 9803 1028 4624]
 [   0    0    0    0 2049 9803 1028 3501]
 [   0    0    0    0 2049 5814 1028 1820]
 [   0    0    0 9909 1124 9391 3507 5988]
 [   0    0    0 9909 1124 9391 3507 4877]
 [   0    0    0 7266 2049 1365 1028 3779]
 [   0    0    0    0 3233 3884 7809 3507]]


In [40]:
### feature representation
dim = 10
model = Sequential()
model.add(Embedding(voc_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [41]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [42]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 73ms/step


array([[[-0.04061729,  0.03073683, -0.0460229 ,  0.02417468,
         -0.0051972 , -0.02202473,  0.00258106, -0.04682092,
          0.022881  , -0.00809182],
        [-0.04061729,  0.03073683, -0.0460229 ,  0.02417468,
         -0.0051972 , -0.02202473,  0.00258106, -0.04682092,
          0.022881  , -0.00809182],
        [-0.04061729,  0.03073683, -0.0460229 ,  0.02417468,
         -0.0051972 , -0.02202473,  0.00258106, -0.04682092,
          0.022881  , -0.00809182],
        [-0.04061729,  0.03073683, -0.0460229 ,  0.02417468,
         -0.0051972 , -0.02202473,  0.00258106, -0.04682092,
          0.022881  , -0.00809182],
        [-0.0200143 , -0.00434643, -0.02500467,  0.00165472,
         -0.01539797, -0.00108169,  0.04055386, -0.01002485,
         -0.00292712,  0.03296044],
        [-0.03533846,  0.02505554, -0.04561377, -0.01698004,
          0.02298805, -0.02837025, -0.02962167,  0.01208978,
         -0.04283163, -0.03835408],
        [-0.02585538, -0.01852107, -0.04063205,  0.0

In [43]:
embedded_docs[0]

array([   0,    0,    0,    0, 2049, 9803, 1028, 4624])